version: '3.8'

services:
  exoplanet:
    container_name: exoplanet-service
    build:
      context: .
      dockerfile: Dockerfile.exoplanet
    ports:
      - "3003:3003"
    networks:
      - exoplanet-network

  fuelestimation:
    container_name: fuelestimation-service
    build:
      context: .
      dockerfile: Dockerfile.fuelestimation
    ports:
      - "6000:6000"
    networks:
      - exoplanet-network

networks:
  exoplanet-network:
    driver: bridge
