SERVICE_NAME: "sample-microservice"
GIN_RELEASE_MODE: "debug"
DB_NAME: "sample_database"
DB_USER: "postgres"
DB_PASSWORD: "postgres"
DB_HOST: "localhost"
DB_PORT: 5432
DB_LOG_MODE: true
DB_SSL_MODE: "disable"
DB_CONNECTION_POOL:
  MAX_OPEN_CONNECTIONS: 30
  MAX_IDLE_CONNECTIONS: 10
  MAX_IDLE_TIME: 300
  MAX_LIFE_TIME: 3600
  TIMEOUT: 30

APP_HOST: "0.0.0.0"
APP_PORT: "3003"

LOG_LEVEL: "debug"

SERVICE:
  EXTERNAL_SERVICE_ENDPOINT: "0.0.0.0:6002"
